{
    "PopoverItems": [{
            "Title": "Add Supplier_bid_table",
            "OnPress": "/n4/Actions/Supplier_table/NavToSupplier_table_CreateSupplier_bid_table.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/n4/Rules/Supplier_table/Supplier_table_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}